version: '3'

services:
  server:
    build: docker/nginx
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  app:
    build: docker/php/7.2
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_IDE_CONFIG: "serverName=localhost"
    links:
      - db
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
    working_dir: /app

  db:
    image: postgres:13-alpine
    volumes:
      - ./database/pgsql/data:/var/lib/postgresql/data
      - ./:/app
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    working_dir: /app
    ports:
      - "5432:5432"
